IF NOT EXISTS (SELECT * FROM sys.databases WHERE name = 'CarRentalDB')
BEGIN
    CREATE DATABASE CarRentalDB;
END
GO

USE CarRentalDB;
GO

IF NOT EXISTS (SELECT * FROM INFORMATION_SCHEMA.TABLES WHERE TABLE_NAME = 'Cars')
BEGIN
    CREATE TABLE Cars (
        id INT PRIMARY KEY IDENTITY(1,1),
        name NVARCHAR(100) NOT NULL,
        year INT NOT NULL,
        price DECIMAL(10, 2) NOT NULL,
        mileage INT NOT NULL,
        rented BIT NOT NULL
    );
END
GO
